FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
RUN echo "test"
# RUN dotnet new tool-manifest
# RUN dotnet tool install dotnet-ef
# WORKDIR /src/Identity/Identity.Infrastructure
# COPY . .
# ENTRYPOINT [ "dotnet" ]
# CMD [ "tool", "run", "ef", "database", "update" ]